"""Unit tests for the baseline hygiene check. Real scratch baseline files, same no-mocking
convention as this package's other tests.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pytest

from py_ci_shared.baseline_hygiene import (
    assert_baseline_is_honest,
    body_asserts_only_absence_of_crash,
    find_baseline_problems,
)

_GOOD_NOTE = "kept: the painter is a decorative leaf and isolating it costs a layer"


def _json_baseline(tmp_path: Path, accepted: dict) -> Path:
    p = tmp_path / "empty-catch.json"
    p.write_text(json.dumps({"_comment": "managed by baseline.py", "accepted": accepted}, indent=2), encoding="utf-8")
    return p


class TestNotes:
    def test_entry_without_a_note_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": ""})
        problems = find_baseline_problems(p)
        assert len(problems) == 1
        assert "no human reason" in problems[0]

    def test_autogenerated_note_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": "pre-existing"})
        assert len(find_baseline_problems(p)) == 1

    def test_real_note_passes(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": _GOOD_NOTE})
        assert find_baseline_problems(p) == []

    def test_note_requirement_can_be_disabled(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": ""})
        assert find_baseline_problems(p, require_notes=False) == []


class TestStaleAndAbsolutePaths:
    def test_stale_entry_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/gone.dart#0": _GOOD_NOTE})
        problems = find_baseline_problems(p, current_violations=["lib/other.dart#0"])
        assert len(problems) == 1
        assert "no longer violate" in problems[0]

    def test_present_entry_is_not_stale(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": _GOOD_NOTE})
        assert find_baseline_problems(p, current_violations=["lib/a.dart#0"]) == []

    def test_windows_absolute_path_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"C:\\Users\\Admin\\repo\\lib\\a.dart#0": _GOOD_NOTE})
        problems = find_baseline_problems(p)
        assert any("absolute path" in x for x in problems)

    def test_posix_home_path_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"/home/ci/repo/lib/a.dart#0": _GOOD_NOTE})
        assert any("absolute path" in x for x in find_baseline_problems(p))


class TestTextAllowlist:
    def test_text_allowlist_without_reason_is_flagged(self, tmp_path):
        p = tmp_path / "shared-test-allowlist.txt"
        p.write_text("# header comment\nwidgets/x.dart\n", encoding="utf-8")
        problems = find_baseline_problems(p)
        assert len(problems) == 1
        assert "no human reason" in problems[0]

    def test_text_allowlist_with_reason_passes(self, tmp_path):
        p = tmp_path / "shared-test-allowlist.txt"
        p.write_text(f"widgets/x.dart  # {_GOOD_NOTE}\n", encoding="utf-8")
        assert find_baseline_problems(p) == []


class TestTakeExceptionOnly:
    def test_take_exception_alone_is_not_an_assertion(self):
        assert body_asserts_only_absence_of_crash("await tester.pumpWidget(w);\nexpect(tester.takeException(), isNull);")

    def test_take_exception_with_a_real_assertion_is_fine(self):
        assert not body_asserts_only_absence_of_crash("expect(tester.takeException(), isNull);\nexpect(find.text('hi'), findsOneWidget);")

    def test_body_without_take_exception_is_not_matched(self):
        assert not body_asserts_only_absence_of_crash("expect(1, 1);")


class TestAssert:
    def test_assert_passes(self, tmp_path):
        assert_baseline_is_honest(_json_baseline(tmp_path, {"lib/a.dart#0": _GOOD_NOTE}))

    def test_assert_fails(self, tmp_path):
        with pytest.raises(pytest.fail.Exception, match="no human reason"):
            assert_baseline_is_honest(_json_baseline(tmp_path, {"lib/a.dart#0": ""}))
