"""Unit tests for the baseline hygiene check. Real scratch baseline files, same no-mocking
convention as this package's other tests.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pytest

from py_ci_shared.baseline_hygiene import (
    assert_baseline_is_honest,
    body_asserts_only_absence_of_crash,
    find_baseline_problems,
)

_GOOD_NOTE = "kept: the painter is a decorative leaf and isolating it costs a layer"


def _json_baseline(tmp_path: Path, accepted: dict) -> Path:
    p = tmp_path / "empty-catch.json"
    p.write_text(json.dumps({"_comment": "managed by baseline.py", "accepted": accepted}, indent=2), encoding="utf-8")
    return p


class TestNotes:
    def test_entry_without_a_note_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": ""})
        problems = find_baseline_problems(p)
        assert len(problems) == 1
        assert "no human reason" in problems[0]

    def test_autogenerated_note_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": "pre-existing"})
        assert len(find_baseline_problems(p)) == 1

    def test_real_note_passes(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": _GOOD_NOTE})
        assert find_baseline_problems(p) == []

    def test_note_requirement_can_be_disabled(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": ""})
        assert find_baseline_problems(p, require_notes=False) == []


class TestStaleAndAbsolutePaths:
    def test_stale_entry_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/gone.dart#0": _GOOD_NOTE})
        problems = find_baseline_problems(p, current_violations=["lib/other.dart#0"])
        assert len(problems) == 1
        assert "no longer violate" in problems[0]

    def test_present_entry_is_not_stale(self, tmp_path):
        p = _json_baseline(tmp_path, {"lib/a.dart#0": _GOOD_NOTE})
        assert find_baseline_problems(p, current_violations=["lib/a.dart#0"]) == []

    def test_windows_absolute_path_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"C:\\Users\\Admin\\repo\\lib\\a.dart#0": _GOOD_NOTE})
        problems = find_baseline_problems(p)
        assert any("absolute path" in x for x in problems)

    def test_posix_home_path_is_flagged(self, tmp_path):
        p = _json_baseline(tmp_path, {"/home/ci/repo/lib/a.dart#0": _GOOD_NOTE})
        assert any("absolute path" in x for x in find_baseline_problems(p))


class TestTextAllowlist:
    def test_text_allowlist_without_reason_is_flagged(self, tmp_path):
        p = tmp_path / "shared-test-allowlist.txt"
        p.write_text("# header comment\nwidgets/x.dart\n", encoding="utf-8")
        problems = find_baseline_problems(p)
        assert len(problems) == 1
        assert "no human reason" in problems[0]

    def test_text_allowlist_with_reason_passes(self, tmp_path):
        p = tmp_path / "shared-test-allowlist.txt"
        p.write_text(f"widgets/x.dart  # {_GOOD_NOTE}\n", encoding="utf-8")
        assert find_baseline_problems(p) == []

    def test_a_comment_heading_explains_the_entries_under_it(self, tmp_path):
        # The convention in both consuming repos: one sentence introducing a group. Demanding a
        # per-line note reported eighteen entries that were already explained.
        p = tmp_path / "shared-test-allowlist.txt"
        p.write_text(
            "# Platform-conditional stubs and thin SDK wrappers, covered indirectly:\n" "analytics/core_analytics.dart\n" "utils/shared_log.dart\n",
            encoding="utf-8",
        )
        assert find_baseline_problems(p) == []

    def test_a_blank_line_ends_the_heading_s_reach(self, tmp_path):
        p = tmp_path / "shared-test-allowlist.txt"
        p.write_text(
            "# Platform-conditional stubs, covered indirectly by their callers:\n" "analytics/core_analytics.dart\n" "\n" "widgets/unexplained.dart\n",
            encoding="utf-8",
        )
        problems = find_baseline_problems(p)
        assert len(problems) == 1
        assert "unexplained.dart" in problems[0]


class TestTakeExceptionOnly:
    def test_take_exception_alone_is_not_an_assertion(self):
        assert body_asserts_only_absence_of_crash("await tester.pumpWidget(w);\nexpect(tester.takeException(), isNull);")

    def test_take_exception_with_a_real_assertion_is_fine(self):
        assert not body_asserts_only_absence_of_crash("expect(tester.takeException(), isNull);\nexpect(find.text('hi'), findsOneWidget);")

    def test_body_without_take_exception_is_not_matched(self):
        assert not body_asserts_only_absence_of_crash("expect(1, 1);")


class TestAssert:
    def test_assert_passes(self, tmp_path):
        assert_baseline_is_honest(_json_baseline(tmp_path, {"lib/a.dart#0": _GOOD_NOTE}))

    def test_assert_fails(self, tmp_path):
        with pytest.raises(pytest.fail.Exception, match="no human reason"):
            assert_baseline_is_honest(_json_baseline(tmp_path, {"lib/a.dart#0": ""}))


def test_the_entries_list_and_core_record_shapes_are_checked(tmp_path):
    listed = tmp_path / "a.json"
    listed.write_text(json.dumps({"schema": 1, "entries": ["lib/a.dart", "lib/b.dart"]}), encoding="utf-8")
    problems = find_baseline_problems(listed)
    assert len(problems) == 2 and "'lib/a.dart'" in problems[0] and "'entries'" not in "".join(problems)
    record = tmp_path / "b.json"
    record.write_text(json.dumps({"entries": {"lib/a.dart": {"count": 2, "note": _GOOD_NOTE}, "lib/b.dart": {"count": 1, "note": ""}}}), encoding="utf-8")
    problems = find_baseline_problems(record, current_violations=["lib/a.dart", "lib/b.dart"])
    assert len(problems) == 1 and "'lib/b.dart'" in problems[0]
    stale = find_baseline_problems(record, current_violations=["lib/a.dart"], require_notes=False)
    assert len(stale) == 1 and "lib/b.dart" in stale[0]


@pytest.mark.parametrize(
    "key",
    ["/opt/app/src/x.py", "/tmp/x.py", "/root/x.py", "/github/workspace/src/x.py", "\\\\server\\share\\x.py", "D:\\work\\x.py", "e:/x.py"],
)
def test_every_absolute_key_is_flagged(tmp_path, key):
    problems = find_baseline_problems(_json_baseline(tmp_path, {key: _GOOD_NOTE}))
    assert len(problems) == 1 and "absolute path" in problems[0]


@pytest.mark.parametrize("note", [_GOOD_NOTE + " (read/write split)", _GOOD_NOTE + " see /api/v1/items and https://x.org/a"])
def test_a_relative_key_with_slashes_in_its_note_is_not_absolute(tmp_path, note):
    assert find_baseline_problems(_json_baseline(tmp_path, {"src/x.py": note})) == []


def test_a_note_in_another_script_counts_its_words(tmp_path):
    ok = _json_baseline(tmp_path, {"src/x.py": "оставлено: декоративный слой, изоляция стоит дороже"})
    assert find_baseline_problems(ok) == []
    short = _json_baseline(tmp_path, {"src/x.py": "оставлено навсегда"})
    assert len(find_baseline_problems(short)) == 1
