"""Shared check: a baseline of accepted violations stays a decision, not a landfill.

The baseline pattern ("freeze today's violations, fail on new ones") is only honest while three
things hold. All three broke in the 2026-09-02 glossum / flutter_app_core audit round:

1. **Every accepted entry carries a human reason.** An entry whose note is the scanner's own
   auto-generated sentence records that a violation existed, not that anyone decided to keep it
   (flutter_app_core C03-6: 18 such entries; glossum P04-16). The whole point of a baseline over a
   blanket ignore is that a reader can see why.
2. **A stale entry fails.** An entry for a violation that no longer exists means the baseline is
   describing a codebase that is gone; nobody notices, and the next real violation slots into the
   gap (flutter_app_core C02-14: seven allowlist lines for files that had tests by then). Reporting
   it and continuing is what let them survive.
3. **No absolute paths.** ``C:\\Users\\...`` or ``/home/...`` in a committed baseline makes it match
   on exactly one machine and silently accept everything everywhere else (C03-4).

Plus one rule about what counts as an assertion, because it is the same class of self-deception:
``expect(tester.takeException(), isNull)`` as a test's ONLY assertion asserts that nothing threw,
which is what the framework already reports; a test whose name promises behaviour and whose body
proves absence-of-crash is a smoke test wearing the name (glossum P04-14).

Deliberately dependency-free (``json`` + ``re``); works on any baseline shaped as ``{"accepted":
{key: note}}`` or ``{key: note}``, and on a plain-text allowlist of ``path  # reason`` lines.

Usage::

    from py_ci_shared.baseline_hygiene import assert_baseline_is_honest

    def test_baselines_carry_reasons():
        for path in (REPO / "tool" / "meta" / "baselines").glob("*.json"):
            assert_baseline_is_honest(path, current_violations=scan(path.stem))
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable, Mapping
from pathlib import Path

_ABSOLUTE_PATH_RE = re.compile(r"(?:^|[\s\"'(])(?:[A-Za-z]:[\\/]|/(?:home|Users|mnt|c)/)")
# A note that is only the scanner's own sentence: no prose a human would write. The heuristic is
# deliberately loose -- it asks for SOMETHING beyond the machine text, not for good writing.
_AUTOGENERATED_NOTE_RES = (
    re.compile(r"^\s*$"),
    re.compile(r"^(?:accepted|baselined|pre-existing|existing|grandfathered|TODO|FIXME)\.?\s*$", re.IGNORECASE),
    re.compile(r"^(?:auto|autogenerated|generated)\b", re.IGNORECASE),
)
_MIN_NOTE_WORDS = 4


def _entries(baseline_path: Path) -> dict[str, str]:
    """Return ``{key: note}`` from a JSON baseline (``accepted`` map or bare map) or a text
    allowlist of ``value  # reason`` lines."""
    text = baseline_path.read_text(encoding="utf-8", errors="replace")
    if baseline_path.suffix == ".json":
        data = json.loads(text)
        accepted = data.get("accepted", data) if isinstance(data, dict) else {}
        out: dict[str, str] = {}
        if isinstance(accepted, dict):
            for key, value in accepted.items():
                if key.startswith("_"):
                    continue
                out[key] = value if isinstance(value, str) else json.dumps(value)
        elif isinstance(accepted, list):
            for item in accepted:
                out[str(item)] = ""
        return out
    out = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, _, note = stripped.partition("#")
        out[key.strip()] = note.strip()
    return out


def find_baseline_problems(
    baseline_path: Path,
    *,
    current_violations: "Iterable[str] | None" = None,
    require_notes: bool = True,
) -> list[str]:
    """Return one problem string per note-less entry, stale entry, or absolute path.

    ``current_violations`` is the scanner's present-day output for the same rule; when given, an
    accepted key absent from it is reported as stale. Pass ``None`` to skip that rule (e.g. when
    the scanner is expensive to run from the test that checks hygiene).
    """
    entries = _entries(baseline_path)
    problems: list[str] = []
    name = baseline_path.name

    for key, note in sorted(entries.items()):
        blob = f"{key} {note}"
        if _ABSOLUTE_PATH_RE.search(blob):
            problems.append(
                f"{name}: entry {key[:70]!r} contains an absolute path - it matches on one machine " f"and silently accepts everything on every other."
            )
        if require_notes:
            words = len(re.findall(r"[A-Za-z]{2,}", note))
            if any(p.match(note) for p in _AUTOGENERATED_NOTE_RES) or words < _MIN_NOTE_WORDS:
                problems.append(
                    f"{name}: entry {key[:70]!r} has no human reason ({note[:40]!r}). A baseline "
                    f"entry records a DECISION; without the why it is an ignore with extra steps."
                )
    if current_violations is not None:
        current = set(current_violations)
        stale = sorted(k for k in entries if k not in current)
        if stale:
            problems.append(
                f"{name}: {len(stale)} accepted entry(ies) no longer violate the rule - the "
                f"baseline is describing a codebase that is gone, and the next real violation "
                f"slots into the gap. Prune:\n    " + "\n    ".join(s[:100] for s in stale[:15])
            )
    return problems


def assert_baseline_is_honest(
    baseline_path: Path,
    *,
    current_violations: "Iterable[str] | None" = None,
    require_notes: bool = True,
) -> None:
    """Fail on a note-less entry, a stale entry, or an absolute path in ``baseline_path``."""
    import pytest

    problems = find_baseline_problems(baseline_path, current_violations=current_violations, require_notes=require_notes)
    if problems:
        pytest.fail(f"{len(problems)} baseline hygiene problem(s):\n  " + "\n  ".join(problems))


_ONLY_TAKE_EXCEPTION_RE = re.compile(r"expect\(\s*(?:await\s*)?tester\.takeException\(\)\s*,\s*isNull\s*\)")
_ANY_EXPECT_RE = re.compile(r"\bexpect(?:Later|Async)?\s*\(|\bassert\b|\bverify\s*\(")


def body_asserts_only_absence_of_crash(body: str) -> bool:
    """True when the only assertion in ``body`` is ``takeException(), isNull``.

    Exposed separately so a repo's own assertion scanner can call it: such a test proves the
    framework did not report an error, which the framework already does, while its NAME claims the
    behaviour is covered.
    """
    if not _ONLY_TAKE_EXCEPTION_RE.search(body):
        return False
    without = _ONLY_TAKE_EXCEPTION_RE.sub("", body)
    return not _ANY_EXPECT_RE.search(without)
