"""The list of every module this package ships, with what it is and how it is run.

One entry per public module under ``py_ci_shared``, kept in ``registry.toml`` next to this file (data, so the list
does not count against the module-size budget). ``tests/test_package_inventory.py`` fails when a module is
neither here nor in :data:`INTERNAL_MODULES`, when a registered gate has no test file or no README line, or when
a registered entry function or CLI ``main`` does not exist. The README gate catalogue is rendered from this list
(:func:`render_catalogue`), and the ``py-ci-shared`` CLI and the pytest plugin look gates up here.

Fields of :class:`GateSpec`:

- ``name``: the module name under ``py_ci_shared``.
- ``kind``: ``"gate"`` (has ``assert_*`` entry functions a consumer calls or enables in ``[tool.py_ci_shared]``),
  ``"cli"`` (a command-line tool, run with ``py-ci-shared tool <name>`` or ``python -m py_ci_shared.<name>``)
  or ``"library"`` (scanners and helpers a consumer wraps in its own test).
- ``entries``: the ``assert_*`` functions, the first being the default the plugin and ``run`` call.
- ``since``: the first release that shipped the module.
- ``budget_s``: runtime budget per call in seconds; the plugin and ``run-all`` warn past it and, in ``fail`` mode,
  fail past it.
- ``cli``: the module has a ``main`` and a ``__main__`` guard.
- ``tests``: test files covering it, when not ``tests/test_<name>.py``.
"""

from __future__ import annotations

import pkgutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

__all__ = [
    "GATES",
    "REGISTRY_FILE",
    "INTERNAL_MODULES",
    "GateSpec",
    "by_name",
    "discover_modules",
    "load_gates",
    "render_catalogue",
    "unregistered_modules",
]

CATALOGUE_START = "<!-- gate-catalogue:start (generated by `py-ci-shared list --markdown`; do not edit by hand) -->"
CATALOGUE_END = "<!-- gate-catalogue:end -->"


@dataclass(frozen=True)
class GateSpec:
    """One public module of the package."""

    name: str
    kind: str
    entries: tuple[str, ...]
    since: str
    budget_s: float = 30.0
    cli: bool = False
    summary: str = ""
    tests: tuple[str, ...] = ()

    @property
    def module(self) -> str:
        return f"py_ci_shared.{self.name}"

    @property
    def test_files(self) -> tuple[str, ...]:
        return self.tests or (f"tests/test_{self.name}.py",)

    @property
    def default_entry(self) -> Optional[str]:
        return self.entries[0] if self.entries else None


# Modules that are not part of the public surface: the package plumbing and the private helpers of other modules.
INTERNAL_MODULES: dict[str, str] = {
    "_gate_report": "the shared scan-and-report plumbing of the single-rule gates",
    "_gate_run": "the shared assert_* tail of the AST gates",
    "_consumers": "the consumer repo list and the read-only checkout the scheduled consumer jobs run",
    "_core": "shared reader, corpus, scan, baseline, refresh, aliases and config every gate builds on",
    "_mutation_fingerprint": "private part of mutation_teeth",
    "_mutation_model": "private part of mutation_teeth",
    "_mutation_operators": "private part of mutation_teeth",
    "_mutation_runner": "private part of mutation_teeth",
    "_scaffold": "the ``py-ci-shared new-gate`` scaffolder",
    "_mutation_worker": "subprocess worker of mutation_teeth; its stdout is the protocol",
    "_toml_compat": "tomllib on 3.11+, tomli before",
    "cli": "the ``py-ci-shared`` console script",
    "pytest_plugin": "the ``pytest11`` plugin behind ``[tool.py_ci_shared]``",
    "registry": "this module",
}

REGISTRY_FILE = Path(__file__).resolve().parent / "registry.toml"


def load_gates(path: Path = REGISTRY_FILE) -> tuple[GateSpec, ...]:
    """The specs in *path* (``registry.toml`` shipped next to this module), in file order."""
    from ._toml_compat import tomllib

    data = tomllib.loads(path.read_text(encoding="utf-8"))
    return tuple(
        GateSpec(
            name=g["name"],
            kind=g["kind"],
            entries=tuple(g.get("entries", ())),
            since=g["since"],
            budget_s=float(g.get("budget_s", 30.0)),
            cli=bool(g.get("cli", False)),
            summary=g.get("summary", ""),
            tests=tuple(g.get("tests", ())),
        )
        for g in data.get("gate", [])
    )


GATES: tuple[GateSpec, ...] = load_gates()

_BY_NAME: dict[str, GateSpec] = {spec.name: spec for spec in GATES}


def by_name(name: str) -> GateSpec:
    """The spec for *name* (module name; dashes are accepted for underscores). Raises ``KeyError`` naming the choices."""
    key = name.replace("-", "_")
    try:
        return _BY_NAME[key]
    except KeyError:
        raise KeyError(f"unknown py-ci-shared module {name!r}; `py-ci-shared list` shows every registered one") from None


def discover_modules(package_dir: Optional[Path] = None) -> list[str]:
    """Every top-level module and subpackage name under the installed ``py_ci_shared`` (or *package_dir*)."""
    root = package_dir if package_dir is not None else Path(__file__).resolve().parent
    return sorted(info.name for info in pkgutil.iter_modules([str(root)]))


def unregistered_modules(package_dir: Optional[Path] = None) -> list[str]:
    """Modules that exist on disk but are neither in :data:`GATES` nor in :data:`INTERNAL_MODULES`."""
    return [m for m in discover_modules(package_dir) if m not in _BY_NAME and m not in INTERNAL_MODULES]


def _md(text: str) -> str:
    return text.replace("|", "\\|")


def render_catalogue(repo_url: str = "src/py_ci_shared", gates: Optional[tuple[GateSpec, ...]] = None) -> str:
    """The README gate catalogue: one table row per module of *gates* (default :data:`GATES`), between the markers."""
    lines = [
        CATALOGUE_START,
        "",
        "| module | kind | since | entry | what it checks |",
        "|---|---|---|---|---|",
    ]
    for spec in GATES if gates is None else gates:
        entry = f"`{spec.default_entry}`" if spec.default_entry else ("`main`" if spec.cli else "")
        if len(spec.entries) > 1:
            entry += f" (+{len(spec.entries) - 1})"
        lines.append(f"| [`{spec.name}`]({repo_url}/{spec.name}.py) | {spec.kind} | {spec.since} | {entry} | {_md(spec.summary)} |")
    lines += ["", CATALOGUE_END]
    return "\n".join(lines)
